language: java
jdk:
  - oraclejdk8
before_script:
  - chmod +x ds/gradlew
script:
  - ./ds/gradlew check
  - ./ds/gradlew codeCoverageReport
after_success:
  - if [ -e ./ds/gradlew ]; then ./ds/gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)
